travis:
  secure:
    BINSTAR_TOKEN: GnslmBeeVC0gUbugd7D9vFWyEXivTwkxEAH0omME1Rj7pcIKzSPXVxc64qo8vrrPqNcYj4/kK97h7n28zkuvfS0SC1nBC5qOGBXDqKYOwQGmUPk8etmsUQuokGqW8pe/PnknJHBNmScZTf2b2lvpWicJBZh7kzJ251yJzD4BM5I/ehT2qs9otkXVcM8M98fA2Qd/Kq1A81KnEsWEyjNPJntA/wHDY2+cgpUc8GEPLi0ISXJR8piFmZ65TSAbhNcOcf7pctqq9scGY2O6DXR6VCLZafi35On9vy6sQQonA9tCXoUDLJbnl+7IwPcM6ieGMar+/oWKPzHMQc4WyYGYp4qAqdKIFb6z8AP0FFf2KZ0ah4MAXVfhL51i20UhgSJp1s3oHsDzqt1sjgmeqeFNVe9hu6CNxh6Yt6eznhM7Iq4+geSDcJzfQx8sazclrfrkB/R6fpNI4Xx1Nzj/33VyzHMA24JgOS0xkLka+ha2w/3sHNp69aPx63RnylaFhEI67EhGFzZdS6xUnlzNcL7bkHaRVGue/bJVZmqzMYR76zABQIDxs3HTMTAcKUfVLJE5sMvoJeck2ji7L33rt95x64C+CT+qv8QO0GxtiMbsM7eyNT+Mm/ACQ0KtqtS+GGoHJZfBdn8C9jNdVegk1xJ55WL+i16FTVnyMbYUwgS6v20=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
