travis:
  secure:
    BINSTAR_TOKEN: gIGvkt9wSfiZ2Bt/SXyrjbM3Wve9ZylnYdhAVQDS4o8tu1ciBqdIUvswjrf+c8VGk8/JIr+y0fDXvGBmWSKdFe3idEHKk5Gd3UAvjfoaIfDGKr+MJ4cflCuZch2qzMAyn/ZylxUouQsYNUMV25/a3K17Z1olViEki2v/MBk4FbdTRz+WNo4nxF5ltiLAIgXEd0v3aLCXgIUQaWgn57hgeR/cD1TiiLE0LSBfTcpcwlYW+X7295wFVzHcjePysPdfQpofKWjqWI3zu/3/bmfjz7qIbcKel2fuuM/AkEdOwx6JL4oLTdMckunqVdfxKvkNeIqOIy8MeZ2OcUdFfdGe0AWUm+wdoEIzn9cd13575V4DpVb3I95cMcroU0G2m9p7vTe2vQ7dVF4WbFZh3HWcEyvbQ86qC6gmMkX/sZz41nc1pF921FDFPiNXbIRPo0/atmccI7qzDpFbdIsYYw+GlB2QkxH5HtrBSSV0o9M/CZFpJ8luaqnucaKqlO4nzC9sTY/X2RoS1vADP3Lxcs6Vrj4VJBzt0NT8qwhBX00TZTnywqqJBM8DM72mTg1/Pn/WXfhRzaC7Yb+1FZOZLv7KYfm3M/o0gtowXgJP3KHGCf2HCCp/b8WjlsugQ5Q/PH9O6WeB2PFB6K/l01xQ2WSA2Tftmxb2PfOpm7y1qW9r2pA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
